name: Decompress LZ77 Test

on:
  workflow_dispatch:

jobs:
  decompress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Wiimms SZS Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget make gcc
          wget https://szs.wiimm.de/download/szs-tools.tar.gz
          tar -xzf szs-tools.tar.gz
          cd szs-tools*
          sudo make install

      - name: Run decompression
        run: |
          mkdir output
          for file in input/*; do
            echo "Processing $file"
            wszst decompress "$file" --dest output/ || echo "Failed to decompress $file"
          done

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: decompressed-files
          path: output/
